[package]
name = "cargo-installer"
version = "0.1.0"
edition = "2024"

[dependencies]
egui = "0.32.1"
expectest = "0.12.0"
iced = "0.13.1"
lazy_static = "1.5.0"
ribir = "0.3.0"
slint = "1.12.1"
test-case = "3.3.1"
trunk = "0.21.14"
yew = "0.21.0"
